### ISSUE TITLE
provide setInitalDelay() for javax.ws.rs.client.Invocation

### ISSUE THREAD

**Issue by nimo23** [eclipse-ee4j/jaxrs-api#771]
If I want to put some **poll delay** within the jax-rs client, I have to use something like this:

```
try {
Invocation invocation = webTarget.request().buildGet();
Thread.sleep(2000);
invocation.invoke(String.class);
} catch (InterruptedException e) {
Thread.currentThread().interrupt();
}
```

However, using `Thread.sleep` within jee-container is not good..

Maybe, the **initial delay** can be supported by a new method `setInitalDelay()` for `Invocation`. So something like this can be used to start the GET request after initial delay:

```
Invocation invocation = webTarget.request().initialDelay(2000).buildGet();
invocation.invoke(String.class);
```

or 

```
Invocation invocation = webTarget.request().buildGet();
invocation.initialDelay(2000).invoke(String.class);
```

Or are there any other solutions for jax-rs? Maybe with async jax rs?

**Comment by spericas** [comment]
In the _synchronous_ case, the end result will not be different to what you're doing now. In the _async_ case, it could make a bit more sense. 

 OTOH, the notion behind delays, retries, etc. is easily abstracted away so that it can be used with different APIs. This is what libraries such as Hystrix and more recently MicroProfile Fault Tolerance have done. I suggest that you take a look at those; I bet you'll find other interesting features there as well.

**Comment by chkal** [comment]
I agree with @spericas. This looks like a very special use case and something like this should be addressed on a different layer and is out of scope of the core API.

**Comment by nimo23** [comment]
With `setInitalDelay` JAX-RS can provide a mechanism to avoid excessive polling (e.g. DoS) with its `javax.ws.rs.client.Client`.  The method should be put into the responsible layer which is JAX-RS.

**Comment by spericas** [comment]
@nimo23 Please close this issue if you agree with what was suggested above.
