### ISSUE TITLE
Does javax.ws.rs-javax.ws.rs-api-2.0-m10 support for Java 11? If not, any timeline or recommendation?

### ISSUE THREAD

**Issue by xinmin-zhou** [eclipse-ee4j/jaxrs-api#860]
Hi Expert,
I would appreciate if you could share your knowledge related with me? Thanks.

Regards,
Xinmin

**Comment by mkarg** [comment]
It dendends on what you mean with "support".
* The API JAR file itself is able to be used on JRE 11 in the CLASSPATH but it is not a module (it neither contains an explicit nor automatic module constraint); it was compiled on JDK 6.
* The API JAR does not explicitly use any particular language feature, interface or class which was added to the JRE after JRE 6.
* The various implementations ("products") of this API MAY support JRE 11, but you need to ask these vendors about their products' abilities.

I wonder why you are using this outdated milestone instead of the latest JAX-RS 2.0 or 2.1 version? In particular, there is a perfect inplace-substitute for your JAR, which is already compiled on JDK 8: https://search.maven.org/artifact/jakarta.ws.rs/jakarta.ws.rs-api/2.1.6/bundle.
