### ISSUE TITLE
HttpHeader for Expect 

### ISSUE THREAD

**Issue by senivam** [eclipse-ee4j/jaxrs-api#900]
will it be possible to add after [this line](https://github.com/eclipse-ee4j/jaxrs-api/blob/739605d01db73c522779dd43897bf86c8709ad2d/jaxrs-api/src/main/java/jakarta/ws/rs/core/HttpHeaders.java#L199) HttpHeader for Expect? 
```
    /**
     * See <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.20">HTTP/1.1 documentation</a>.
     */
    public static final String EXPECT = "Expect";
```

this is required to provide support for HTTP 100-continue handling (see related [Jersey bug](https://github.com/eclipse-ee4j/jersey/issues/4536) about this)

**Comment by andymc12** [comment]
Yes, I think it makes sense to add the Expect header to the list in `HttpHeaders`. Can you open a pull request adding these lines?  Make sure to target the `3.1-SNAPSHOT` release since we cannot add it to the 3.0 (master) release.  Thanks!

**Comment by mkarg** [comment]
@andymc12 I agree with you, but just for my own curiosity: What do you expect to break if we add a new `static String` to this interface? IMHO it would be safe to do it even in `master`, as nobody would say this is really a feature, and we keep backwards compatibility.

**Comment by senivam** [comment]
so, just to be clear, shall I do the PR or @mkarg will do that? And how to proceed? :)

**Comment by andymc12** [comment]
@mkarg 
> What do you expect to break if we add a new static String to this interface? IMHO it would be safe to do it even in master, as nobody would say this is really a feature, and we keep backwards compatibility.

Nothing should break, afaik, but my understanding was that Jakarta EE 9 was supposed to be binary compatible with Jakarta EE 8 except for the package name change.  I would also recommend putting this into 3.1 since @spericas just released 3.0 - I think we could probably re-spin the release, but even if it is allowed to add to 3.0, I don't think this change is worth the trouble to re-spin.  If others think strongly that it should go into 3.0, I can be persuaded - but we'd probably want somebody from the platform community to approve first. @spericas @kwsutter @ivargrimstad wdyt?

@senivam if you are ok with waiting until 3.1, then you could open the pull request.  If you want to push for inclusion into 3.0, then I would suggest waiting until Santiago or somebody from the platform committee agrees. Thanks!

**Comment by spericas** [comment]
Yes, this should be 3.1. Looks like @mkarg already set that.

**Comment by mkarg** [comment]
@senivam Do you confirm that your wanted changes are contained in the 3.1 branch, so we can close this issue? Thanks.

**Comment by senivam** [comment]
@mkarg yes, sure, the issue can be closed as resolved. Thank you.
