### ISSUE TITLE
Missing status codes in Response class

### ISSUE THREAD

**Issue by reschke** [eclipse-ee4j/jaxrs-api#993]
See <https://github.com/eclipse-ee4j/jaxrs-api/pull/582>, which was closed for reasons that escape me.

There are likely more status codes missing, see the IANA registry at <https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml>. It would also be good to update comments to refer to current RFCs, not obsoleted ones.

cc: @mkarg

**Comment by spericas** [comment]
The reason is there:

 "@mithunsasidharan Are you still interested in working on this? If so, could you rebase against `3.1-SNAPSHOT" and update the pull request accordingly?" 

Needs to be resubmitted for 3.1 using the correct branch.

**Comment by mithunsasidharan** [comment]
@spericas : Is this something thats already been pickedup ? If not I'd like to work on it !

**Comment by spericas** [comment]
@mithunsasidharan Feel free to work on it. See previous work and suggestion by @reschke.

**Comment by spericas** [comment]
@mithunsasidharan Any update on this work?

**Comment by jelemux** [comment]
Sorry for the late response, I've caught the flu and then had a week of vacation after I recovered.

I went through all the missing status codes and singled those out that MAY be of general interest for REST applications.  
I've documented my findings on [this wiki page](https://github.com/jelemux/jaxrs-api/wiki/Missing-status-codes). Feel free to go through them and comment your opinions here.

In short, those are the status codes that may be of _general_ interest to REST applications:
* [203 Non-Authoritative Information](https://tools.ietf.org/html/rfc7231#section-6.3.4) 
* [300 Multiple Choices](https://tools.ietf.org/html/rfc7231#section-6.4.1) 
* [308 Permanent Redirect](https://tools.ietf.org/html/rfc7538)
* [451 Unavailable For Legal Reasons](https://tools.ietf.org/html/rfc7725)

I think it is best to create separate PRs for each of these since there may be arguments against some of these that don't concern the others.  
The only exception being the argument that those are all only _Proposed Standard_ RFCs, which has already been [discussed](https://github.com/eclipse-ee4j/jaxrs-api/pull/582), but with no clear conclusion (to me). Does this argument still stand?

**Comment by jelemux** [comment]
What may not be of _general_ interest to REST applications but still came up is WebDAV.  
The [JAXRS specification states under goals](https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html#goals):

> The API will provide high level support for common HTTP usage patterns and will be sufficiently flexible to support a variety of HTTP applications **including WebDAV** and the Atom Publishing Protocol.

Because additional status codes can be added by creating an implementation of `StatusType`, it is my opinion that this goal is fulfilled since the API is _sufficiently flexible_. If you (and others) agree, then I don't think that further discussion on this topic is necessary.

**Comment by andymc12** [comment]
@jelemux I agree with your assessment on the wiki.  I'm +1 for adding 300, 308 and 451.  I'm +0 or -1 on the rest. I also agree that separate PRs would be the most expedient - I suspect that 308 will be the easiest to get in, while 300 and 451 might take some discussion.  Thanks for putting this together!  I think it will also help us in the future (for example, when JAX-RS officially supports HTTP/2, etc.) to know which HTTP response codes we should add.

**Comment by mkarg** [comment]
I never needed 203; I doubt that it is actually of common use.

WebDAV is definitively an outdated technology which we should not start to explicitly support. In fact, if someone wants to use WebDAV with JAX-RS, he can simply use the ready-to-use extension [WebDAV for JAX-RS](https://search.maven.org/artifact/net.java.dev.webdav/jaxrs) which (for those who don't know) was the reason for me adding the `StatusType` interface back then, and which in fact simply does what you propose... (it's always good to know some history ;-) ).

**Comment by jelemux** [comment]
Now that the codes have been added, I think this can be closed now.
